#!/usr/bin/env bash
#
# lib/cleanup.sh — sourced file, DO NOT RUN DIRECTLY
#
# This file is `source`d by systemReport.sh. Running it on its own does
# nothing and dies on the variables it expects. The shebang is only there so the
# linter recognises the file as shell.
#
# systemReport — cleanup.sh
#
# Keeps the number of report folders bounded.
#
# Version 3.1 deleted old folders without asking: data loss dressed up as a
# convenience. Two runs in the wrong place, or one report you wanted to compare
# against, was enough to lose it. Here the newest N reports are kept and the rest
# are deleted, still without asking, but always printing what was deleted.
#
# Sorting is by name. Folder names are arch_report_YYYYMMDD_HHMMSS, so
# alphabetical order is chronological order and no timestamp parsing is needed.
#
# Sorting by name is also the weak point: a report whose folder name was
# generated by a wrong system clock sorts to the wrong end. So the rules are:
#   1. This run's own folder is never in the list (see below).
#   2. When the order cannot be trusted, keeping too many is better than
#      deleting too much, so KEEP_REPORTS is a floor and not a threshold.
#
# Depends on: $REPORT_ROOT, $REPORT_PREFIX, $KEEP_REPORTS, $REPORT_DIR,
#            $CLEANUP_ENABLED

prune_old_reports() {
	[ "$CLEANUP_ENABLED" = 1 ] || {
		warn "Skipping old report cleanup (config: CLEANUP_ENABLED=0 / --noclean)."
		return 0
	}

	local all=() dir count

	# Only folders matching this tool's naming scheme. Because find is limited
	# to -maxdepth 1, every match sits directly under the report root, so a
	# folder of the user's own that happens to be named similarly cannot be
	# caught.
	#
	# THIS RUN'S FOLDER IS EXCLUDED. Sorting is chronological only as long as
	# the clock is right: with a report folder dated in the future, the folder
	# just created sorts as the oldest and the script deletes its own output.
	# This was reproduced during testing.
	while IFS= read -r dir; do
		[ -n "$dir" ] || continue
		# find -print emits FULL paths, so the comparison must be on full
		# paths too. Comparing basenames never matches and the bug persists
		# silently.
		[ "$dir" = "$REPORT_DIR" ] && continue
		all+=("${dir##*/}")
	done < <(find "$REPORT_ROOT" -mindepth 1 -maxdepth 1 -type d \
		-name "${REPORT_PREFIX}_*" -print 2>/dev/null | sort -r)

	# sort -r puts the newest first; the first KEEP_REPORTS entries are kept.
	local i
	count="${#all[@]}"
	[ "$count" -gt "$KEEP_REPORTS" ] || {
		printf '  Report count is within the limit (%s/%s), nothing to clean.\n' \
			"$count" "$KEEP_REPORTS"
		return 0
	}

	warn "Cleaning up old reports: $count found, $KEEP_REPORTS kept, $((count - KEEP_REPORTS)) to delete."

	local base
	for ((i = KEEP_REPORTS; i < count; i++)); do
		dir="${all[i]}"
		# Second line of defence: only paths directly under the report root
		# that matched the name pattern are ever removed.
		base="$REPORT_ROOT/$dir"
		case "$base" in
		"$REPORT_ROOT"/*) ;;
		*)
			err "Safety: unexpected path skipped: $base"
			continue
			;;
		esac
		if [ "${GZIP_OLD_REPORTS:-0}" = 1 ]; then
			_gzip_report "$base" "$dir"
		elif rm -rf -- "$base" 2>/dev/null; then
			printf '  deleted: %s\n' "$dir"
		else
			err "could not delete: $base"
		fi
	done
}

# gzip a single report directory into <name>.tar.gz next to it. Called by
# prune_old_reports when GZIP_OLD_REPORTS=1. Failure falls back to plain
# deletion so a compression problem never causes unbounded growth.
_gzip_report() {
	local base="$1" name="$2" src_size dst_size

	src_size="$(du -sb "$base" 2>/dev/null | cut -f1)"
	src_size="${src_size:-0}"

	if [ -e "$base.tar.gz" ]; then
		warn "archive already exists, deleting instead: $name.tar.gz"
		rm -rf -- "$base" 2>/dev/null && printf '  deleted: %s\n' "$name"
		return 0
	fi

	if tar -czf "$base.tar.gz" -C "$REPORT_ROOT" "$name" 2>/dev/null; then
		rm -rf -- "$base" 2>/dev/null
		dst_size="$(stat -c %s "$base.tar.gz" 2>/dev/null)"
		dst_size="${dst_size:-0}"
		printf '  gzipped: %s -> %s.tar.gz  (%s -> %s KB)\n' \
			"$name" "$name" \
			"$((src_size / 1024))" "$((dst_size / 1024))"
	else
		err "gzip failed, falling back to delete: $name"
		rm -rf -- "$base" 2>/dev/null && printf '  deleted: %s\n' "$name"
	fi
}
